### ISSUE TITLE
Long value support in MutableContext

### ISSUE THREAD

**Issue by pbhandari9541** [open-feature/ofep#39]
**Issue:** [MutableContext](https://github.com/open-feature/java-sdk/blob/main/src/main/java/dev/openfeature/sdk/MutableContext.java) doesn't allow us to add Long value.
`i.e  public MutableContext add(String key, Long value) `

wondering if there is a plan to support long value?

**Our use case:**  Customer provides userId of long value type and we are adding in a context as String. Eventually, we need to convert to long value later. if  MutableContext supports long value, we may mandate customer to enter long value directly.

**Comment by toddbaert** [comment]
`MutableContext` is just one implementation of `EvaluationContext`, which extends `Structure`. I think you should be able to extend it or implement your own that includes `Long`.

However, I think we could support `Long` in `MutableContext` while maintaining backwards compatibility by since all values in the context are stored as plain objects.

**Comment by justinabrahms** [comment]
Agree with Todd. Do you want to file a pull request for this, @pbhandari9541 ?

**Comment by beeme1mr** [comment]
Closing this issue since it's a implementation detail of the Java SDK.
